version: '3.8'

services:
  crewai-job-assistant:
    build: 
      context: ../..
      dockerfile: src/docker/Dockerfile
    container_name: crewai-job-assistant
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONPATH=/app
    env_file:
      - ../../.env
    volumes:
      # Mount data directory for persistence
      - ../../src/data:/app/src/data
      - ../../src/outputs:/app/src/outputs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: crewai-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - crewai-job-assistant
  #   restart: unless-stopped

networks:
  default:
    name: crewai-network